# Generated by Django 4.0.4 on 2022-05-16 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_video_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='date_uplaoded',
            new_name='date_uploaded',
        ),
        migrations.AddField(
            model_name='comment',
            name='date_uploaded',
            field=models.DateField(blank=True, null=True),
        ),
    ]
