# Generated by Django 4.0.4 on 2022-05-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_date_uplaoded_video_date_uploaded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(help_text='Upload a video file', upload_to='my_tube/video/static'),
        ),
    ]
