# Generated by Django 4.0.4 on 2022-06-01 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0009_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(default={'slug': '<django.db.models.fields.related.OneToOneField>'}, unique=True),
        ),
    ]
