# Generated by Django 4.0.4 on 2022-06-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0010_alter_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
